### PR TITLE
[1.1.1] Label fixes

### PR DESCRIPTION
**Pull request by KrisSiegel**
This fixes an issue with the x and y axis labels where they were not clearing properly. Also tiny adjustments to scale the font a little better and to pad the x axis a little less.

@immuta/developers

### CODE REVIEW

**Comment by KrisSiegel** [comment]
I forgot I found another bug related to tooltips so I'm going to fix that real quick. Closing for now.

**Comment by KrisSiegel** [comment]
Okay good. Please review asap peoples.

**Comment by jeffmhastings** [comment]
Since you said please... :+1:

**Comment by barryhammen** [comment]
:+1:

**Pull request merged**
